name: fastai
channels:
  - conda-forge
  - pytorch
  - fastai
dependencies:
  - pytorch==1.4.0
  - torchvision==0.5.0
  - cuda92
  - fastprogress
  - fastai==1.0.57
  - jupyter
  - jupyterlab
  - pip:
      - nvidia-ml-py3
      - dataclasses